# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e21e92114ddacc418264ccfb8512a2cdc66c87d740656807817a8dc7263aaf5e5a11e49089651dda30c50ea0fb86923eb13cc62a6a82acfd040124fd88cbb4b3

test:
  secret_key_base: 55a44765b76b80e8ab285448a5c1c1ee3c13ef5f0583366c9be0ebdf8dada5dbb618948627da463ee94ffa5660104cbff9c14b89383ca88b475cdf509e10f220

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
